### ISSUE TITLE
Any benchmarks to compare to other maps?

### ISSUE THREAD

**Issue by coderedart** [Licenser/halfbrown#12]
Kinda new to this, my apologies if its a dumb request.
I was wondering if some benchmarks could be added to more clearly show the use cases which suit this crate. 
operations that could be benchmarked are probably insert/remove/iteration/get.
1. against std::collections::hashmap with and without a Vec Backend of lengths 32 and maybe above
2. against hashbrown / ahashmap in a similar way. 

if different key sizes favor certain backends. maybe having a `u32` as a key, will go very fast when comparing against a Vector of `u32`, even at larger capacities. but, will it change if the keys are large like Strings or maybe 512 byte numbers (sha512 hashes). 

is 32 elements the ideal length or does it change based on key/value sizes due to cache misses. (like with Huge values)

I ask because i am too newbie and benchmarking seems to be a very complicated subject, and some kind of rough data on README would be super helpful to judge whether people are actually using it for the right job.

**Comment by mfelsche** [comment]
There are benchmarks comparing this one against hashbrown and `std::collections::HashMap` in the `benches` folder.
