### ISSUE TITLE
Store Vec backend on stack instead of heap

### ISSUE THREAD

**Issue by corvusrabus** [Licenser/halfbrown#20]
Hi,

I was thinking that since the Vec backend is fixed to 32 entries it would maybe make sense to use an array to store entries instead of a vector. Then the map would be entirely on the stack. I expect that small maps are anyway the main use case of users of this crate. 

The drawback would, of course, be larger stack usage. As a compromise, one could use a [smallvec](https://docs.rs/smallvec/latest/smallvec/) with 10 entries on the stack. In my use case, I rarely have more than 5 entries in the map.

I would be willing to implement these changes if people think that they are useful.

**Comment by Licenser** [comment]
I like it!

For context, the whole fixed size code is there from before const generics were a thing. Today it could probably be solved with a const generic that defines the size.

smallvec or even an own one stack version totally makes sense, perhaps it could be behind a feature flag so people can switch?

**Comment by corvusrabus** [comment]
I haven't had time to finish this yet but there are some things that need to be thought about. I started implementing a pure stack version with the [arrayvec](https://docs.rs/arrayvec/latest/arrayvec/) crate as the backend (is adding that new dependency fine?). Then the HashMap will by default store 32 entries on the stack but users can change that number if they like. 

One needs to be absolutely sure that you never push anything beyond the capacity because the arrayvec crate will panic then. In the current implementation of halfbrown there is the bug (or feature?) that if you add more entries via the entry() or raw_entry() methods it will never switch the backend from a vector to a hashbrown map. Only using the insert() function will change the backend once 32 entries are reached. If I use a stack backend, I will need to change that logic and make entry() and raw_entry() change the backend as well when the capacity is full.

Is it also your understanding that entry and raw entry should change the backend if necessary? Or was there a problem that prevented it from being implemented that way?

**Comment by Licenser** [comment]
Heya, no worries, neither had I so it's just fair ;)

That's definitely a bug, while I would like to claim that's well thought out and was planned that way, it wasn't and it doesn't make sense that it's not changing the backend. This definitely is a good catch!

So in plain words: entry/raw_entry should definitely switch backends when adding!

**Comment by YjyJeff** [comment]
Any updates? I am looking forward to this new feature

**Comment by corvusrabus** [comment]
Hi sorry, I have already written parts of it but have forgotten about it

**Comment by Licenser** [comment]
slightly related, I looked at the const generic option for size and well it doesn't work well since rust doesn't allow it to be defaulted in impls and that way it'll break the UX of the API

**Comment by corvusrabus** [comment]
> slightly related, I looked at the const generic option for size and well it doesn't work well since rust doesn't allow it to be defaulted in impls and that way it'll break the UX of the API

Maybe that's not a problem if we call the actual Implementation "GenericHashMap" or something like that and then we type alias HashMap to be a GenericHashMap with 32 entries on the stack?

**Comment by Licenser** [comment]
It'd be a option. The basic thing I want to maintain is being able to do replace `std::collection::HashMap` with `halfbrown::HashMap`. Perhaps we can go the opposite route and do `SizedHashMap` ?

But I really like the idea of having a type for it 👍 good thinking

**Comment by corvusrabus** [comment]
> It'd be a option. The basic thing I want to maintain is being able to do replace `std::collection::HashMap` with `halfbrown::HashMap`. Perhaps we can go the opposite route and do `SizedHashMap` ?

Agreed, SizedHashMap is obviously the better name.

**Comment by Licenser** [comment]
I'll make a PR for that since I got the rest of it done, that way you can base your work on the const generic implementation of the map :)

**Comment by Licenser** [comment]
I've published this as `v0.2.0` thanks so much @corvusrabus !
