### ISSUE TITLE
halfbrown::Iter

### ISSUE THREAD

**Issue by dtolnay** [Licenser/halfbrown#4]
I started seeing this failure in code that used to work:

```console
error[E0603]: enum `Iter` is private
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.16/src/serde/value/borrowed/de.rs:63:19
   |
63 |     i: halfbrown::Iter<'de, Cow<'a, str>, Value<'a>>,
   |                   ^^^^
```

Was this type mistakenly removed from the public API?

**Comment by Licenser** [comment]
Ja that was a mistake :) and should be fixed somewhere in the last 2 years later ... I'm terrible at github, sorry
